devwilliamy/coverland

package-lock.json
package.json
src/components/PDP/CarSelector.tsx
src/components/PDP/components/DeliveryDate.tsx
src/components/hooks/useMount.tsx

Made an update to the PDP page where delivery date is determined based on client's time zone.
**Fixes # (issue)**: Skype Request:
> Delivery by OCT 18 - PST time zone: Before 2 PM, show delivery as 2 days later (e.g., if today is JAN 11, it should display JAN 13). After 2 PM, the date should change to JAN 14.
> 
> MST time zone: Show delivery as 1 extra day later than PST. Display JAN 14 before 2 PM and JAN 15 after 2 PM.
> 
> CST time zone: Show delivery as 1 extra day later than MST. Display JAN 15 before 2 PM and JAN 16 after 2 PM.
> 
> EST time zone: Show delivery as 1 extra day later than CST. Display JAN 16 before 2 PM and JAN 17 after 2 PM.
> 
> 
> If this task takes some time, you can simply display the delivery date as 2 days from today, which is JAN 13, before 2 PM, and 3 days …

[GO-LIVE-FIXES] Determine Delivery Date by Time Zone

---

src/components/PDP/CarSelector.tsx
src/components/PDP/components/EditVehiclePopover.tsx
src/components/PDP/components/SubDropdowns.tsx
src/components/PDP/components/SubmodelSearch.tsx
src/components/PDP/components/SubmodelSearch2nd.tsx

- Had issue where if you had submodel and submodel2, title wasn't reflected properly
- Select your vehicle had issues selecting properly
- Submodel2 wasn't being filtered properly based on submodel1
- Now filters submodel2 based on submodel1 selection
- Fixed default value when only submodel1 was picked and submodel2 is needed
- Now shows full product name
Test cases:
Test going to PDP w/o selecting submodel
Test selecting the submodel first and then the second submodel on the PDP page.
Test selecting both on the PDP page.
Test different combinations of these and other trucks and regular cars with submodels
- truck-covers/gmc/sierra-1500/2014-2018?&submodel=crew+cab&second_submodel=5.5+ft.+short+bed
- truck-covers/gmc/sierra-1500/2014-2018?&submodel=crew+cab&second_submodel=6.5+ft.+regular …

[PDP] Updated SubmodelSearch and Submodel2Search and Titles for Submodel2

---

src/app/(main)/car-covers/components/CarPDP.tsx
src/app/(main)/car-covers/components/ColorSelector.tsx
src/components/PDP/EditVehicleDropdown.tsx
src/lib/utils.ts

- Fixed edge case where certain second_submodel strings wouldn't match the submodel2_slug stored in DB (e.g. non-us+version vs. non-us-version)
- Included utility function for more accurately comparing strings

Additional bug fixes

---

src/app/(main)/car-covers/[make]/[model]/[year]/page.tsx
src/lib/db/index.ts

- Addressed edgecase where generation is it's own parent generation (e.g. cars that only display one type of car in one year generation, with no other submodels)

Hotfix for hero dropdown (car selection)

---

src/app/(main)/car-covers/components/CarCoverSelector.tsx
src/components/PDP/CarSelector.tsx

- When a car has a submodel but it's not selected, it said to "Please finish your selection" 
- Calvin didn't want it so took that out and it just says Cover Color now

[CK-Request] Updated text to always show cover color even when submodel not selected

---

src/components/PDP/components/ModelSearch.tsx
src/components/PDP/components/SubDropdowns.tsx
src/components/PDP/components/SubmodelSearch.tsx
src/components/PDP/components/SubmodelSearch2nd.tsx

- Ties submodel selection to actual user action of submitting dropdown rather than checking the value during the render

Fixing bug on SUV/Truck pages w/ no submodel

---

src/app/(main)/car-covers/components/PartialCoverSelector.tsx
src/app/(main)/policies/warranty-policy/page.tsx
src/components/PDP/CarSelector.tsx
src/components/PDP/MobilePDPAccordions.tsx
src/components/PDP/PDPAccordian.tsx
src/components/PDP/components/WarrantyDesktop.tsx
src/components/hero/dropdown/MakeSearch.tsx
src/components/hero/dropdown/ModelSearch.tsx
src/components/hero/dropdown/SubmodelDropdown.tsx
src/components/hero/dropdown/TypeSearch.tsx
src/components/hero/dropdown/YearSearch.tsx
src/components/home/BestSellingSection.tsx
src/components/home/CoversGrid.tsx
src/components/home/TrendingCarsSection.tsx
src/components/icons/ReviewRatingStar.tsx
src/pages/home/HomepageReviews.tsx

[CK-Request] Home Page Fixes And Some

---

src/app/(main)/[productType]/components/ProductContent.tsx

- Ensuring that the modelData accessed by the Add To Cart selection fields use values (such as submodels) that are based on the filtered data. This will prevent users from selecting options for products that won't work.

Minor update for filtering

---

src/app/(main)/[productType]/components/CarPDP.tsx
src/components/PDP/MobilePDPDetails.tsx
src/components/PDP/OtherDetails.tsx
src/components/PDP/components/ReviewSection.tsx

Forgot to commit this in the last PR.
Added year params to store so it was easier for me to detect what page we were on and if we needed to use the parent generation year for searching.

Added Year Params to Store

---

src/hooks/useGoogleTagDataLayer.ts

- Removed unique colors from dependency array to make it stop re-rendering multiple times

Fixing Multiple Re-rendering which caused Google Tag to fire events multiple times

---

src/hooks/useGoogleTagDataLayer.ts

From Calvin:
> From the google ad manager:
> 
> Remove the discount, since we transfer the promotional price, the discount can be considered again. To avoid duplication, you need to remove it.

Removed discount from gtag temporarily

---

src/app/(main)/policies/shipping-policy/page.tsx
src/app/(main)/policies/warranty-policy/page.tsx
src/components/PDP/MobilePDPDetails.tsx
src/components/PDP/components/ExtraDetailsTabs.tsx
src/components/PDP/components/ReviewSection.tsx
src/components/policy/PolicyHeader.tsx

- This change can be found in ExtraDetailsTabs component
- This is a Calvin request and cannot be found in figma

Hiding inner navigation bar for "Warranty" and "Shipping and Returns"

---

src/lib/db/review/index.ts
src/lib/db/types.ts

Until we start having actual pictures, updated the getReviewImages to use an RPC from supabase to automatically get distinct review images.
It's better for the database to have that strain for this kind of task rather than getting a lot of data on the server and filtering there.
- Verify review images match what is on production
- Verify on car/suv/truck covers
- Verify images look good on all the different review spots (see more customer images, etc)

Updated get review images to use an RPC.

---

src/app/(main)/[productType]/[coverType]/page.tsx
src/app/(main)/[productType]/components/AddToCart.tsx
src/app/(main)/[productType]/components/FeaturesAndProductsSection.tsx
src/app/(main)/[productType]/components/SeeAllSectionClientWrapper.tsx
src/components/PDP/components/MobileProductDetails.tsx
src/middleware.ts

Ex: https://coverland.com/car-covers/pontiac/safari/1958-1964 shows error
Should go to https://coverland.com/car-covers/premium-plus/pontiac/safari/1958-1964
- Test different options on different product types
- Test other cover types still work
- Test with submodels and submodel 2
- Just try to break it 
- Check SuggestProducts does not show
- IF a user does like /car-covers/prem it'll do /car-covers/premium-plus/prem. I think this is fine for now since users should just not misspell shit y'kno but if this is a problem, we can look into a fuzzy search library to help autocorrect

If Premium-Plus is not in the URL, redirect to it. Remove Suggested Products

---

src/components/policy/ReturnPolicyContent.tsx

- Replaced email of ReturnPolicyContent from returns@coverland.com to info@coverland.com

Changing returns@coverland.com -> info@coverland.com

---

src/components/footer/Footer.tsx

- Routed instagram footer link to english page instead of korean

Replaced footer instagram link

---

src/hooks/useGoogleTagDataLayer.ts

Something was causing Google Tag to bomb out so just going to have null check here just in case

Added some null checks for google tag

---

src/app/api/meta/event/route.ts
src/app/api/sku-labs/orders/route.ts
src/components/checkout/PayPalButtonSection.tsx
src/components/checkout/Payment.tsx
src/contexts/CheckoutContext.tsx
src/lib/utils/date.ts
src/lib/utils/skuLabs.ts

It is time consuming for CSRs to create a new order whenever someone purchases a product.
We want to be able to send SKU Labs customer information to help reducing CSR workload
Important documentation here:
https://app.clickup.com/t/8688px0k2
https://app.clickup.com/t/8688qcn4c
1. Purchase an order on Coverland.com
2. Verify order is successfully purchased and you go to thank you page.
3. Verify order shows up in SKULabs
4. Verify order details are correct in SKU Labs
5. Test for both Stripe and Paypal

Implemented SKU Lab Order Creation Upon Payment Confirmation

---

src/components/checkout/PayPalButtonSection.tsx
src/components/checkout/Payment.tsx
src/lib/utils/skuLabs.ts

CSRs requested seeing whether it is Paypal/Stripe in SKU Lab notes
Also had a discrepancy when user typed in something different from Paypal, made it hard to find so going to send SKU Lab info from Paypal instead. 
1. Pull code down locally
2. Remove "PREVIEW" checks
3. Go through checkout process w/ stripe, verify Stripe appears in notes in SKU Labs (ask someone)
4. Go through checkout process w/ Paypal, verify Paypal appears in notes in SKU Labs and shipping address info lines up with what was in Paypal

Added Payment gateway to SKU Lab & Map Paypal Info to SKU Lab instead of user input

---

src/components/checkout/PayPalButtonSection.tsx

Sometimes there's a discrepancy  between Paypal shipping info and what the customer input.
We're reverting back to sending SKU Labs the customer input, but we will save paypal shipping to admin panel for the time  being.

Reverted paypal skulab shipping info back to customer input

---

src/components/checkout/SavedShippingBox.tsx
src/components/checkout/ShippingOptions.ts
src/components/checkout/ShippingSelection.tsx

Original text had FedEx because that was in the design. We aren't using FedEx at all for shipping at the moment.  Updating shipping text to make more sense.

Updated shipping text to say USPS or UPS

---

src/app/(main)/[productType]/components/LinkBreadcrumbs.tsx
src/app/(main)/[productType]/components/ProductContent.tsx
src/app/(main)/seat-covers/components/SeatContent.tsx
src/components/edit-vehicle/EditVehicleModal.tsx
src/components/edit-vehicle/EditVehiclePopover.tsx

The PDP product title should have the matching casing and symbols from the EditVehicleDropdown
Live:

Updating Product Display Title to use selectedProdcut value in store

---

src/app/(main)/[productType]/components/CircleColorSelector.tsx
src/app/(main)/[productType]/components/ProductContent.tsx
src/app/(main)/seat-covers/components/SeatContent.tsx

Need to make the Klarna Image appear on the same line as the installments:
Also per Calvin request:
- Move Klarna 1px up and reduce the left side gap
- Installment text 14->16px 
- Installment price weight 400->500

Fixing PDP Klarna installment image spacing 

---

src/app/api/sku-labs/orders/status/webhook/route.ts

https://app.clickup.com/t/8688r0kt4
In order to add yourself to the webhook go here: https://next.skulabs.com/settings#advanced/api
You will need login info from Calvin, or ask Mark/Ji to help with adding this
Example:
When you create it and someone changes the status of an order in SKU Labs, that will get sent to that API URL. You should be able to see logs of how it works in the logs.
Ask Mark / Ji to help with changing status or explaining how to change the status.
1. In Payment.tsx, take `generateSkuLabOrderInput` and the `skuLabCreateOrderResponse` fetch out of the "PREVIEW" check
2. Submit an order
3. Confirm a TEST order shows up in SKU Labs
4. Change the status
5. Observe logs

Added route for sku labs order status webhook

---

src/app/(main)/[productType]/components/FreeDetails.tsx
src/app/(main)/seat-covers/components/SeatContent.tsx
src/app/(main)/seat-covers/components/SeatCoverColorSelector.tsx
src/components/PDP/EditVehicleDropdown.tsx
src/components/cart/AddToCart.tsx
src/components/cart/AddToCartButton.tsx
src/lib/db/index.ts
src/lib/db/seat-covers/index.ts
src/lib/db/types.ts

Unfortunately two changes in this PR I should have made the other one a different PR
https://app.clickup.com/t/86889zcb1
When on an incomplete year page or on a submodel/submodel2 page, when you try to edit the vehicle and use the same type, make, model, and year parameters, the selected product won't update.
This is caused by Next.js thinking there are certain components that just use the search params and just does a soft reload. 
In an ideal world, this is the behavior we want and what should happen is that `selectedProduct` and `modelData` get updated depending on the submodel search params. I think the steps to do this is we have to keep a copy of the initial model data because we filter down on it based on submodel. If a search param is added in EditVehicleDropdown, then we just …

Submodel Search Params Not Refreshing Page & Adding IsComplete checks

---

src/lib/utils/deliveryDateUtils.ts

Fixing issue similar to #584
Users outside of our date range were getting Invalid DateTime
Could have sworn "Unknown" worked though so not sure what happened there

Fix Delivery Date For Out Of Range Timezone

---

src/components/checkout/CheckoutAccordion.tsx
src/components/checkout/PayPalButtonSection.tsx
src/components/checkout/PriceBreakdown.tsx
src/lib/utils/date.ts
src/lib/utils/deliveryDateUtils.ts

Calvin wanted the preorder email text to say approximately timeframe in weeks
"The estimated fulfillment timeframe is approximately 4 months from the date of purchase. " ->
"The estimated fulfillment timeframe is approximately 16 weeks from the date of purchase. "

Updated preorder email to say weeks instead of months

---

src/lib/utils/stripe.ts

Having an issue where if a product is purchased but it doesn't exist in our db, the SKU doesn't exist
MX was the default, but this is meant for mixed products
So changing unknown / default to be UN instead

Changed MX to UN for unknowns

---

src/lib/db/constants/databaseTableNames.ts
src/lib/db/sku-labs/index.ts
src/lib/utils/skuLabs.ts

Takes awhile to link items and there's a lot of orders so automating as much as that process as possible.
Need to use the sku-lab-update-quantity project, it's been repurposed to map SKU Labs SKU to ItemID.
That script should work and insert new ones only to the table.
Note: currently doesn't work for full seat sets (these are kits). Will figure that out later.
Also doesn't work for some pre orders if they don't exist in SKU Labs yet. 
Probably have to run the script whenever there's a new preorder sheet.

Links SKU Lab Item to SKU Lab Order

---

src/middleware.ts

Lot of errors in vercel log so went in and put a fix for it.
Might also should be using parent_generation instead of year_generation but I'll come back to it a different time
Might also have to fix year options in the db
```
TypeError: Cannot destructure property 'year_generation' of '(intermediate value)' as it is undefined.
at (src/middleware.ts:167:16)
at (node_modules/next/dist/esm/server/web/adapter.js:157:15)
```

Middleware Year generation destructure log fix

---

src/components/cart/PreorderPreview.tsx

[CK] It seems that when a user clicks on one option and then exits out to click on another, the price keeps adding up. Can you adjust it so that only the price of the selected seat cover is shown, without adding the previous selections?

Updated preorder preview to show discount amount not total amount

---

src/components/hero/dropdown/SubmodelDropdown.tsx

Was having some issues where if the submodel had a different generation, it was possible the wrong parent generation was being picked up.
I added a parent generation update when submodel is picked to update to the parent generation of the submodel1 that was picked.

Dropdown: Update parent generation when submodel1 is selected

---

src/app/api/sku-labs/orders/status/webhook/route.ts
src/components/checkout/CheckoutAccordion.tsx
src/components/checkout/PayPalButtonSection.tsx
src/lib/sendgrid/emails/shipping-confirmation.ts
src/lib/sendgrid/emails/thank-you.ts
src/lib/trustpilot/index.ts

Didn't make sense to send the email for pre orders so we're having the surveys happen when shipping occurs
Should be when order arrives TBH, but we don't have it yet.
Had to update trustPilot function to use TOrderItem instead of TCartItem, there's just a layer of product to dig into for the same information so not a big deal.

TrustPilot Email Sent On Shipping Confirmation Instead Of Thank You Email Now

---

src/lib/sendgrid/emails/shipping-confirmation.ts

Customers getting reviews when not received product yet.
Part of it due to the reviews being sent between 8/15 - 8/29 (when it was upon purchase).
Part of it due to people just printing labels and triggering the shipping confirmation email.
Getting lot of 1* reviews due to people not receiving their product yet.
Removing until end of October ish.

Removing trust pilot from shipping confirmation

---

src/components/checkout/CustomTextField.tsx

Was having an issue where this address wasn't working
Previous validation would check if each word was only 1 letter so this failed.
Updating it to just do 3 characters or more, restricting certain symbols

Changed addressline validation regex

---

src/app/(main)/[productType]/components/CircleColorSelector.tsx
src/app/(main)/seat-covers/components/SeatCoverColorSelector.tsx
src/utils/index.ts

We want to have the same behavior as we have for seat covers.
- In Stock > Preorder
- BKRD > BKGR > GRBK
There were some issues where preorder was not properly being sorted and the initial selection wasn't working correctly when switching to full seat set.
You can use this link to see:
https://coverland.com/seat-covers/leather/alfa-romeo/giulia/2017-2023
Some examples to check on the preview:
/seat-covers/leather/mercedes-benz/s-class/2014-2020?submodel=sedan
/seat-covers/leather/alfa-romeo/giulia/2017-2023
/seat-covers/leather/mazda/cx-5/2013-2024
/seat-covers/leather/toyota/corolla/2014-2019?submodel=sedan

Car Cover Color Arrange & Seat Cover Color Fix

---

src/app/(main)/seat-covers/components/SeatContent.tsx

Only put preorder step 1 check on floor mats because seat covers weren't using the shared component yet

Added in google tag for preorder step 1 for seat covers
