devwilliamy/coverland

- src/app/checkout/page.tsx
- src/pages/home/Header.tsx
- Fixed pricing
- Fixed styling
> -Linked delete item from cart functionality to checkout page.

- src/components/PDP/CarSelector.tsx
- src/components/PDP/DropdownPDP.tsx
- src/components/PDP/components/SubDropdowns.tsx
- src/components/PDP/components/SubmodelSearch.tsx
- src/lib/utils.ts
- added useEffect to SubmodelSearch to properly track state change
- unsure of any side effects tho
- tested the main dropdown and didn't see issues at first
> [PDP] Submodel selection fix where some submodel selections won't trigger a page change

- src/components/PDP/ProductHero.tsx
- src/components/PDP/components/SubDropdowns.tsx
- src/components/hero/HeroSection.tsx
> Commenting out some isMobile and adding useClient to ProductHero

- src/app/(noFooter)/checkout/page.tsx
- src/components/PDP/components/AccordionDrawerItem.tsx
- Font size and color changes
- Trying something else for checkout spinner
- Trying modal size for mobile PDP
> [CK-Request] Checkout Fixes

- src/app/(main)/car-covers/components/CarCoverSelector.tsx
- src/app/(main)/car-covers/components/ProductContent.tsx
- src/components/PDP/CarSelector.tsx
- src/components/PDP/MobilePDPDetails.tsx
- src/components/cart/AddToCartBody.tsx
- src/components/cart/AddToCartFooter.tsx
- src/components/cart/AddToCartHeader.tsx
- src/components/cart/CartSheet.tsx
- src/components/cart/YourCartHeader.tsx
- src/components/header/Cart.tsx
- src/components/ui/bottom-up-drawer.tsx
- src/components/ui/sheet.tsx
- src/lib/cart/useCart.ts
- Header cart is now a "Your Cart"
- Add to Cart will have an "✅ Added to Cart"
- Separated cart opening logic depending on what you do 
- Mobile cart is now a bottom up drawer
- Designs have been updated to look like Figma
- Created components for cart
- Corrected on Mobile PDP some clashing CSS & also updated to appropriate color
To Test:
- Ensure car cover and SUV cover and truck cover add to cart works
- Check both mobile and desktop
- Verify numbers are correct
> [CK-REQUEST] Cart Update To Look Like Figma

- package-lock.json
- src/app/(main)/car-covers/components/ProductContent.tsx
- src/components/cart/AddToCartBody.tsx
- src/components/cart/AddToCartFooter.tsx
- src/components/header/Cart.tsx
- src/components/ui/bottom-up-drawer.tsx
- Quick fix for cart modal -- was showing up too high on phone, trying a different height.
> Reduced height for cart did some PDP add to cart  button changes

- src/app/(main)/car-covers/components/ProductContent.tsx
- src/components/PDP/CarSelector.tsx
- src/components/PDP/MobilePDPDetails.tsx
- src/components/PDP/OtherDetails.tsx
> Star Icon Fix

- src/components/PDP/MobilePDPDetails.tsx
- src/components/PDP/PDPAccordian.tsx
- src/components/PDP/components/AccordionDrawerItem.tsx
- Gave Warranty and Q&A content containers a max height: none -> 60vh
- Unrestricted PDPAccordian max height at large breakpoint due to previous change
> [CK REQUEST] - Increase drawer height of Warranty and Q&A 

- src/components/ui/accordion.tsx
-Added Plus Icon back to AccordionTrigger in accordion.tsx
> [CK REQUEST]  - Add Q&A drawer icons back

- package-lock.json
- package.json
- src/app/(main)/car-covers/components/ProductContent.tsx
- src/app/(noFooter)/checkout/page.tsx
- src/components/PDP/CarSelector.tsx
- src/components/PDP/components/EditVehiclePopover.tsx
- src/components/header/Cart.tsx
- src/components/ui/dialog-tailwind-ui.tsx
~~- old modal wouldn't work on safari~~
~~- tested with calvin and on simulator seems to work~~
Ended up going straight to checkout for now
> Made New Modal Out of Tailwind / HeadlessUI

- src/app/(main)/car-covers/components/ProductContent.tsx
- src/components/PDP/CarSelector.tsx
- Aligned Free Shipping with Delivery Date
> [CK REQUEST] - Align Free shipping and Delivery date 

- src/app/(main)/car-covers/components/ColorSelector.tsx
- src/app/(main)/car-covers/components/MobileImageCarousel.tsx
- src/app/(main)/car-covers/components/PartialCoverSelector.tsx
- src/app/(main)/car-covers/components/PrimaryImageDisplay.tsx
- src/app/(main)/car-covers/components/ProductContent.tsx
- src/components/PDP/CarSelector.tsx
- src/components/PDP/MobilePDPAccordions.tsx
- src/components/PDP/MobilePDPDetails.tsx
- src/components/PDP/OtherDetails.tsx
- src/components/PDP/ProductHero.tsx
- src/components/PDP/ProductVideo.tsx
- src/components/PDP/components/AccordionDrawerItem.tsx
- src/components/PDP/components/ClimateCrisisMobile.tsx
- src/components/PDP/components/EditVehiclePopover.tsx
- src/components/PDP/images/StrongWinds.tsx
- src/components/ui/bottom-up-drawer.tsx
- Fixes nested interactive content that was causing hydration issues 
- Added 'use client' to stateful components that didn't include It 
- Used dynamic import for ReactVideo component that was causing hydration issues (inherently due to the library) 
- Added prop to drawer to prevent modal freezing on scroll in Safari
-- This was caused due to some behavior in Safari that attempted to get around the shrinking and growing address bar)
-Various minor optimizations
> PDP Hydration Bug Fixes + Optimizations

- src/components/PDP/ProductVideo.tsx
- Height of video now fills its container
- Seek backward button / forward button
> Fixing Video Size For Safari

- src/components/PDP/MobilePDPDetails.tsx
- Switched out the drawer component for a sheet
- Seems to work yeet
- No idea tbh
> Changed Drawer to Sheet to fix freezing on iOS Safari

- src/components/hero/HeroSection.tsx
- src/components/home/CoversGrid.tsx
- src/components/home/SecuritySection.tsx
- src/components/home/TrendingCarsSection.tsx
- src/pages/home/DesignedInUSA.tsx
- src/pages/home/HomepageReviews.tsx
- src/pages/home/WhyChooseCoverland.tsx
> Fixing Hydration, Warnings, and Errors on Home page

- src/app/(main)/car-covers/components/MobileImageCarousel.tsx
- src/app/(main)/car-covers/components/PartialCoverSelector.tsx
- src/app/(main)/car-covers/components/PrimaryImageDisplay.tsx
- src/app/(main)/car-covers/components/ProductContent.tsx
- src/components/PDP/CarSelector.tsx
- src/components/PDP/ProductVideo.tsx
- src/pages/home/HomepageVideoSection.tsx
- tsconfig.json
- videos/7sec Listing Video_2.mp4.json
- videos/Coverland_Square.mp4.json
- 7 sec video auto plays in 4th spot in carousel
- 6 min video is removed from carousel and is placed by Add To Cart
> Added 7 Second Video and Moved 6 Minute Video out of Carousel

- src/app/(main)/[productType]/[make]/page.tsx
- src/app/(main)/[productType]/components/ProductContent.tsx
- src/app/(main)/utils/index.ts
- src/lib/constants.tsx
- src/lib/db/index.ts
- Enhanced logic to properly pre-fill dropdowns on PDP
- Fixed conditional disabling of dropdown fields 
- Changes URLs for default images on truck page
> Updates for properly filling Add To Cart Selection

- src/app/(main)/[productType]/[make]/page.tsx
- src/app/(main)/[productType]/components/AddToCart.tsx
- src/app/(main)/[productType]/components/ProductContent.tsx
- src/app/(main)/utils/index.ts
- src/lib/constants.tsx
- src/lib/db/index.ts
Merging femi's changes on main into preview branch
> Merge main into preview

- src/app/(main)/[productType]/components/AddToCart.tsx
- src/app/(main)/utils/index.ts
- src/components/PDP/MobilePDPDetails.tsx
- src/components/PDP/PDP Page Flow.md
- src/lib/db/index.ts
- Resetting state of certain dropdowns when other dropdowns are selected. This prevents invalid selection combinations
> PDP Filtering Fixes

- client.webpack.lock
- server.webpack.lock
- src/app/(main)/[productType]/components/PrimaryImageDisplay.tsx
- src/app/(main)/[productType]/components/ProductContent.tsx
- videos/https_x2kly621zrgfgwll.public.blob.vercel-storage.com_videos_FINALIZE_WEBSTIE_16_9_OPTIMIZED.mp4.json
Depending on performance we may want to get this even smaller.
> Uploading optimized version of 6-min video on PDP (285MB vs 980MB)

- src/components/PDP/components/HelpfulSection.tsx
- src/components/PDP/components/ReviewSection.tsx
- src/lib/db/review/index.ts
Added an input search field to search through review description.
Calvin said to not put it in yet so commenting out for now.
> Search Text Field (is commented out due to Calvin Request)

- src/lib/db/review/index.ts
Was having some issues with special characters not being matched due to what's coming in from the URL and what's saved in the database.
Some example models:
- Skyline GT-R (R34) -> skyline-gt-r-34
- Silverado 1500 -> silverado-1500
- Skyline GT-R (R33) -> skyline-gt-r-r33
- 2500-3.0CS (E9)  -> 2500-3-0CS-e9
Script is also in supabase
```sql
--========================
-- Normalize Make and Model columns for review table 
--========================
-- Create new column for make and model 
ALTER TABLE "reviews-2"
ADD COLUMN make_slug TEXT,
ADD COLUMN model_slug TEXT;
-- Select and normalize the slug 
SELECT  LOWER(
REGEXP_REPLACE(
TRIM(BOTH '-' FROM 
REGEXP_REPLACE(
REPLACE(model, ' ', '-'), 
'[^a-zA-Z0-9-]', 
'', 
'g'
)
), 
'[-]+', '-', 'g'
)
);
-- Update the column
UPDATE "reviews-2"
SET …
```
> Added Slugs to Review Table

- src/app/layout.tsx
- src/app/scripts/AppScripts.tsx
Following this suggestion first:
https://stackoverflow.com/a/77907468
Does look like it's in the <head> tag though
> Removing meta pixel script from app scripts and putting in root layout

- src/lib/db/review/index.ts
- videos/7sec Listing Video_Compressed.mp4.json
It was passing in an empty string so it was searching on empty string
> ProductReviewSummary: If make model not provided, pass in undefined instead

- src/app/(main)/thank-you/components/OrderConfirmationContent.tsx
- src/app/(noFooter)/checkout/page.tsx
- src/app/api/checkout-sessions/route.ts
- Accidentally just committed to preview directly woops
- NlSkeS0v is 99% for Dev
- fnUHD0s8 is 99% for Prod
- Added null checks for if item is empty
- Updated _Orders DB Table
> Allowing Promo Code Entry

- src/app/(main)/[productType]/components/ProductContent.tsx
- src/components/PDP/components/ReviewCard.tsx
- Note: IsComplete isn't working for submodel2, so it'll say it's complete pre maturely but Femi is looking into it
> Removed would recommend if critical review and "From" in price if selection is complete

- src/app/(main)/[productType]/components/FreeDetails.tsx
- src/components/PDP/components/TimeTo2PM.tsx
- Free, same-day shipping was showing a previous day due to it being static
- Updated to use actual time
> Updating free, same-day shipping with actual times

- src/app/(main)/[productType]/components/AddToCart.tsx
- src/app/(main)/[productType]/components/CarCoverSelector.tsx
- src/app/(main)/thank-you/components/OrderConfirmationContent.tsx
- src/app/(noFooter)/checkout/page.tsx
- src/app/api/checkout-sessions/route.ts
- src/hooks/useGoogleTagDataLayer.ts
Created 4 new google tags:
- useItemViewedGoogleTag
- To be run on CarPDP page when it loads
- useCheckoutViewedGoogleTag
- To be run when Checkout Page appears
- useThankYouViewedGoogleTag
- To be run when the thank you page is reached. NOTE: Have to make sure it doesn't send again when you reload the page
- handleAddToCartGoogleTag
- Will be triggered when you successfully add to cart
> Google Tag Updates for PDP and Checkout

- src/app/(main)/[productType]/[coverType]/[make]/[model]/[year]/page.tsx
- src/app/(main)/[productType]/components/CarPDP.tsx
- src/app/(main)/[productType]/components/MobileImageCarousel.tsx
- src/app/(main)/[productType]/components/PrimaryImageDisplay.tsx
- src/app/(main)/loading.tsx
- src/app/scripts/AppScripts.tsx
- src/components/LiveChat.tsx
- src/components/ui/skeleton.tsx
- Added in new live chat and commented out old one #159
> Preview into main

- src/app/layout.tsx
- src/app/scripts/AppScripts.tsx
- Updating tag from G-G2C0X9FH2Z to GTM-PW897Z9Z
> Updating google tag manager

- src/app/scripts/AppScripts.tsx
- src/pages/home/Footer.tsx
- Calvin said needed to do some stuff on the new live chat company side, will let us know when to put in
> Putting old live chat back in

- src/app/(main)/[productType]/components/MobileImageCarousel.tsx
- src/app/(main)/[productType]/components/PrimaryImageDisplay.tsx
- src/app/(main)/[productType]/components/ProductContent.tsx
- Calvin wanted video to stay full screened when rotating video
- Video would disappear when rotating because the component actually disappears 
- Fixed some MD stuff because a lot wasn't showing due to some MD breakpoints
> Full Screen Video Persists on Rotate and Fixing some MD Breakpoints

- src/app/(main)/[productType]/components/CircleColorSelector.tsx
- src/app/(main)/[productType]/components/MobileImageCarousel.tsx
- src/app/(main)/[productType]/components/ProductContent.tsx
- src/components/PDP/EditVehicleDropdown.tsx
- src/hooks/useGoogleTagDataLayer.ts
- Want a view_item google event when clicking on an item
> Fire google event when color changed on product page. Removed some console logs.

- src/app/sitemap.ts
> Sitemap fix

- src/hooks/useGoogleTagDataLayer.ts
- src/lib/utils.ts
- Extracted functions to make updating the event object easier
- Will now account for Premium type etc
- Also deslugified a lot of properties to make it look better when reading
> Updated Google Tags to account for other Cover Types

- src/app/(main)/[productType]/page.tsx
- src/lib/db/constants/databaseTableNames.ts
- src/lib/db/seat-covers/index.ts
- src/lib/db/types.ts
- table name: seat_covers_20240308_duplicate
- For some reason seat_covers_20240308 just wasn't working
> Created Seat Cover API

- src/app/(main)/seat-covers/[seatType]/page.tsx
- src/app/(main)/seat-covers/page.tsx
- src/components/PDP/components/ExtraDetailsTabs.tsx
- src/components/home/CoversGrid.tsx
- Added premium-plus to homepage urls and leatherette to seat cover urls
- Fixed dynamic routing for seat-cover routes
- Extra Details added reviews and qa back to extra details tabs
> Changing Homepage CoverGrid urls

- src/app/(main)/[productType]/components/EditVehiclePopover.tsx
Ex: 
/car-covers/premium-plus/plymouth/business-coupe/1936-1952
> Fixed alignment for edit vehicle popovers Product Name 

- src/app/(main)/[productType]/components/MobileCarouselPositionItem.tsx
- src/app/(main)/[productType]/components/MobileImageCarousel.tsx
- src/components/hero/HeroSection.tsx
- src/lib/db/index.ts
- SUV / Truck defaulting to premium cus it can't find any premium-plus
> Code clean up, re raising fetch count

- src/components/PDP/components/FeaturesSection.tsx
> Fixing Z-index of PDP FeaturedSection 

- src/app/(main)/[productType]/components/LinkBreadcrumbs.tsx
- src/app/(main)/seat-covers/[seatType]/[make]/[model]/[year]/page.tsx
- src/app/(main)/seat-covers/[seatType]/[make]/[model]/page.tsx
- src/app/(main)/seat-covers/[seatType]/[make]/page.tsx
- src/app/(main)/seat-covers/[seatType]/page.tsx
- src/app/(main)/seat-covers/components/CustomForText.tsx
- src/app/(main)/seat-covers/components/DesktopImageDisplay.tsx
- src/app/(main)/seat-covers/components/ElevateComfortSection.tsx
- src/app/(main)/seat-covers/components/EnhancedPerformanceSection.tsx
- src/app/(main)/seat-covers/components/SafetyFirstSection.tsx
- src/app/(main)/seat-covers/components/SeatContent.tsx
- src/app/(main)/seat-covers/components/SeatCoverCarousel.tsx
- src/app/(main)/seat-covers/components/SeatCoverDataWrapper.tsx
- src/app/(main)/seat-covers/components/SeatCoverDetails.tsx
- src/app/(main)/seat-covers/components/SeatCovers.tsx
- src/app/(main)/seat-covers/components/StayNewSection.tsx
- src/app/(main)/seat-covers/page.tsx
- src/components/PDP/components/WarrantySection.tsx
- src/components/hero/dropdown/HomeDropdown.tsx
- src/lib/db/seat-covers/index.ts
- src/lib/db/types.ts
- Sorted colors blk->gr->be with database call
- Modified prices and included "from"
- Double checked image sizing and proportions ( need to confirm for safari mobile)
- Double checked text and padding
- Removed video from seat covers page (will be replaced later)
> Seat Covers Spacing and Font Adjustments

- src/app/(main)/[productType]/components/FreeDetails.tsx
- Added "Includes storage bag, wind-strap, and antenna patch." to "Free $30" section
> Updated PDP Free Details "Free $30" Section 

- src/components/PDP/EditVehicleDropdown.tsx
- Changed EditVehicle Go button to red when enabled
> Edit Vehicle Go Button Change

- src/components/hero/dropdown/HomeDropdown.tsx
- Removed default valuing from the first option in dropdowns. It is now a static title
> Making first option in all dropdowns static  

- src/app/(main)/[productType]/components/ProductContent.tsx
Per Vasiliy
https://coverland.com/car-covers/premium-plus
Waterproof Outdoor Custom-Fit Car Covers
https://coverland.com/suv-covers/premium-plus
Waterproof Outdoor Custom-Fit SUV Covers
https://coverland.com/truck-covers/premium-plus
Waterproof Outdoor Custom-Fit Truck Covers
If car is choosen, then: 
Ford Mustang Car Cover – Waterproof, Outdoor, Custom-Fi
> Removing commas when car isn't selected

- src/middleware.ts
- Redirected any SUV or Truck to Car covers
- Redirected willy's speedway link
> SUV and Truck Redirect to Car Covers

- src/app/(main)/video-review-program/page.tsx
increasing maximum height so that the full form displays
> Google Forms length fix on Video Review Programs page

- src/app/(main)/[productType]/components/ReviewsTextTrigger.tsx
- src/app/(main)/seat-covers/components/SeatCoverReviewSection.tsx
- src/components/PDP/components/ReviewSection.tsx
- src/components/PDP/components/ReviewSheet.tsx
- src/hooks/useDetermineType.ts
- src/lib/utils.ts
Model and Year pages should increment by 100+, 200+, 300+....to 900+ then the actual review number past 999 reviews
> Updating all Review counts to 100(100+) on year and model pages

- src/app/(main)/[productType]/components/LinkBreadcrumbs.tsx
- src/app/(main)/seat-covers/components/SeatContent.tsx
- src/lib/utils.ts
https://app.clickup.com/t/8688mwmbd
> Seat Covers display title adjustments

- next.config.js
- src/app/(main)/[productType]/components/CarCoverSelector.tsx
- src/app/(main)/[productType]/components/DetailsTabHeader.tsx
- src/components/PDP/components/ProductDetailsHeader.tsx
- Retrieved product banner from stores selected product
- Created banner text stylings for car cover PDP
Banner Figma:
https://www.figma.com/design/f0PiJaMbj3moDGXq45iAA1/Coverland-Website-Design?node-id=3916-45265&t=SrTxKKBRoq7UooNN-1
> Dynamic Vehicle Banner for PDP

- src/components/cart/AddToCart.tsx
- src/components/checkout/PayPalButtonSection.tsx
- src/components/checkout/Payment.tsx
- src/lib/utils/skuLabs.ts
Added Payment gateway to SKU Lab & Map Paypal Info to SKU Lab instead of user input #523
> Preview to Main: Added Payment gateway to SKU Lab & Map Paypal Info to SKU Lab

- src/app/(main)/profile/orders/components/OrderItem.tsx
- src/app/(main)/profile/orders/components/OrderList.tsx
- src/app/(main)/profile/orders/page.tsx
- src/app/(main)/profile/page.tsx
- src/components/profile/orders/OrderItemCard.tsx
- src/lib/db/profile/ordersHistory.ts
- src/lib/db/profile/utils/date/index.ts
- src/lib/db/profile/utils/money/index.ts
-Version One
-Click Up : https://app.clickup.com/t/8688pw53e
Figma:
Desktop - https://www.figma.com/design/f0PiJaMbj3moDGXq45iAA1/Coverland-Website-Design?node-id=4577-55056&t=2AMI64xIbxLwMP81-0
Mobile - https://www.figma.com/design/f0PiJaMbj3moDGXq45iAA1/Coverland-Website-Design?node-id=4619-68720&t=2AMI64xIbxLwMP81-0
*Design Notes: Just the orders from the My Account page
** Also Ashley is currently changing some of the design -> that will be rolled out in v2
-New page under /profile/orders
-My Orders returns 4 most recent user orders and displays a list of them with basic details
Test Instructions:
-sign into a user
-go to your profile /profile
-button "My Orders" -> navigates user to /profile/orders
-should output a list of up to 4 most recent user orders (if none, should indicate so) …
> Added new My Orders page to User Profile (v1)

- src/components/hero/dropdown/HomeDropdown.tsx
- src/lib/db/admin-panel/products.ts
- src/lib/db/constants/databaseTableNames.ts
- src/middleware.ts
https://app.clickup.com/t/8688u580m
Product Table Changes:
- MSRP / Price changes
- Mercedes is now Mercedes-Benz
- able to add to cart for car/suv/truck/seat cover (front & back) and finish checkout
- orders and order items are reflected properly
- mercedes now redirects to mercedes-benz
> New Products Table 20240618

- scripts/generateSiteUrls.ts
- src/app/(main)/[productType]/[coverType]/page.tsx
- src/app/(main)/[productType]/page.tsx
- src/app/sitemap.ts
- src/lib/db/index.ts
> Removed suv cover and truck cover unused cover types

- src/app/api/admin-panel/order-items/route.ts
- src/app/api/stripe/payment-intent/route.ts
- src/lib/db/admin-panel/orderItems.ts
- src/lib/db/admin-panel/products.ts
- src/lib/db/types.ts
- src/lib/utils/adminPanel.ts
Order.total_original_amount
Order.total_discount_amount
orderItem.original_price
orderItem.discount_amount
Notes:
These lines are not related; they got changed during auto formatting:
[src/app/api/stripe/payment-intent/route.ts](https://github.com/devwilliamy/coverland/compare/preview...john/preview-original-total-and-discount#diff-8ff4444039cf34cb77ae51d23b658f557f5201aa4d15e8273665183fedb9f88f)
Lines: 37-38, 41-44, 48-52, 54-57, 59-60, 63
Also the file [src/lib/db/admin-panel/orderItems.ts] is not being used by I also updated it to mirror changes to the api/admin-panel/order-items/route.ts
types.ts file: Some new data fields got populated in this that don't involve my changes to the database.
Thank you!
> Updates api routes / handler functions for Order/OrderItems to accept new fields for POST to supabase

- src/lib/db/constants/databaseTableNames.ts
- src/lib/db/review/index.ts
Tables are too big so making them separate.
> Separating Car Cover and Seat Cover Reviews

- src/components/checkout/PayPalButtonSection.tsx
- src/components/checkout/Payment.tsx
Meta, Google, and Microsoft Conversion APIs were being triggered when we would make test purchases 
Turning it off for Dev / Preview environments
> Made it so cAPI don't run on dev environments

- src/components/checkout/PayPalButtonSection.tsx
- src/components/checkout/Payment.tsx
Reverted paypal skulab shipping info back to customer input #549
> Preview to Main: Paypal to SKU Labs - Send Customer Inputted Shipping Info

- src/components/checkout/PayPalButtonSection.tsx
- src/components/checkout/PaymentSelector.tsx
Temporarily removing Paypal due to account freeze #552
> Preview to Main: Temporarily Removing Paypal

- src/middleware.ts
```
- Added to middleware specificUrls redirect:
+ ford/mustang/2005-2024 -> ford/mustang/2005-2025
```
> Ford Mustang 2024 -> 2025 redirect

- src/components/checkout/PaymentSelector.tsx
- src/middleware.ts
Ford Mustang 2024 -> 2025 redirect #551
> Preview to Main: Ford Mustang Redirect

- src/app/(main)/[productType]/components/ProductContent.tsx
- src/app/(main)/seat-covers/components/SeatContent.tsx
- src/app/(main)/seat-covers/components/SeatCoverSelector.tsx
- src/app/api/admin-panel/order-items/route.ts
- src/components/cart/AddToCartBody.tsx
- src/components/checkout/CartItemCard.tsx
- src/contexts/CarSelectionContext.tsx
- src/lib/constants.tsx
- src/lib/db/admin-panel/products.ts
- src/lib/utils.ts
- src/lib/utils/calculations.ts
https://app.clickup.com/t/8688tztnr
> Dynamic prices for low stock products

- src/app/(noFooter)/checkout/utils/index.ts
- src/components/checkout/PayPalButtonSection.tsx
- src/components/checkout/Payment.tsx
- src/components/checkout/PaymentSelector.tsx
Paypal is good again, adding it back in
Added some confirmation / error messages to show after paying
> Added paypal back in, and added some error handling messages

- src/lib/sendgrid/emails/thank-you.ts
Updates the email payload object that gets sent to SendGrid
SendGrid Mailer API V3:
https://www.twilio.com/docs/sendgrid/api-reference/mail-send/mail-send#dynamic-transactional-templates-and-handlebars
> Updates Order Confirmation Email payload object that gets sent to SendGrid

- src/components/checkout/SavedShippingBox.tsx
- src/components/checkout/ShippingOptions.ts
- src/components/checkout/ShippingSelection.tsx
- src/lib/sendgrid/emails/thank-you.ts
Updated shipping text to say USPS or UPS #565
> Preview to Main: USPS & UPS Text Update

- src/components/footer/Footer.tsx
> vasiliy asked me to just change a couple text inside footer

- src/lib/constants.tsx
- Added 0 to lower bound
- Check to make sure Products that have 0 quantity are showing full price
- Make sure products with quantities 3-5 are showing 25% discounted price
- products with quantities above 5 show 50% discounted price
> Low Quantity Price Changes V2

- src/app/api/sku-labs/orders/status/webhook/route.ts
https://app.clickup.com/t/8688yty8n
> changes 500 to 200 status code to prevent reoccuring requests

- src/app/api/sku-labs/orders/status/webhook/route.ts
- src/lib/constants.tsx
https://github.com/devwilliamy/coverland/pull/586
> Shipping Webhook: changes 500 to 200 status code to prevent reoccuring requests 

- src/components/footer/Footer.tsx
- src/components/policy/ContactPage.tsx
- Changed telephone number on home page footer and contact page
- 1-800-799-5165  => 1-888-694-9915
> Home Page and Contact Page: Phone number change

- src/app/(main)/seat-covers/components/SeatContent.tsx
- Removing "Fine" from title of SeatContent
> Seat Cover Page -  Removing "Fine" from product title

- src/components/footer/Footer.tsx
- src/components/policy/ContactPage.tsx
Reverts devwilliamy/coverland#598
> Preview Revert "Home Page and Contact Page: Phone number change"

- src/lib/utils/calculations.ts
No longer need to calculate discount based on quantity due to pre orders
> Removing no discount and 25 percent discount

- src/components/header/Header.tsx
- src/lib/utils/calculations.ts
- src/lib/utils/date.ts
Updated special sale banner with automatically changing months #614
> Preview to Main: Update Special Sale Banner

- src/components/PDP/components/ReviewImagesSheet.tsx
- src/components/header/Header.tsx
Mobile header was still set to June. Will now update automatically
> Fix mobile month

- package-lock.json
- package.json
- src/components/checkout/CheckoutAccordion.tsx
Paypal isn't showing on latest iOS Safari it seems.
Updating the package seemed to fix it, but also seems a little spotty
> Package Update For Paypal

- src/app/(main)/seat-covers/[coverType]/[make]/[model]/[year]/page.tsx
- src/app/(main)/seat-covers/[coverType]/[make]/[model]/page.tsx
- src/app/(main)/seat-covers/[coverType]/[make]/page.tsx
- src/hooks/review/useFilterHandler.tsx
- src/hooks/review/useSortHandler.tsx
- src/hooks/review/useViewMoreHandler.tsx
- src/lib/db/constants/databaseTableNames.ts
- src/lib/db/review/index.ts
Having same seat covers reviews across all make/model/year
Removing all queries for make/model/year for reviews
> New Seat Cover Review DB: Make all seat cover the same across make/model/year

- src/components/PDP/components/ReviewCard.tsx
- src/components/PDP/components/ReviewCardGallery.tsx
- src/components/PDP/components/ReviewHeaderGallery.tsx
- src/components/PDP/components/ReviewImageGalleryDesktop.tsx
- src/lib/db/constants/databaseTableNames.ts
Made images to be object cover so it wouldn't be squished for different dimensions
Removed w-full because it was causing some different sized images to render oddly on the carousel
> Fix for some Review Images being squished

- src/app/(main)/[productType]/[coverType]/[make]/[model]/[year]/page.tsx
- src/app/(main)/[productType]/[coverType]/[make]/[model]/page.tsx
- src/app/(main)/[productType]/[coverType]/[make]/page.tsx
- src/hooks/review/useFilterHandler.tsx
- src/hooks/review/useSortHandler.tsx
- src/hooks/review/useViewMoreHandler.tsx
- src/lib/db/constants/databaseTableNames.ts
- src/lib/db/review/index.ts
Also cleaned up make/model/year from the review functions
> Added new Car Cover Reviews. Removed make year model for car covers. 

- src/components/PDP/components/ReviewCard.tsx
- src/components/PDP/components/ReviewImageGallery.tsx
- src/components/PDP/components/WouldRecomend.tsx
- src/lib/db/review/index.ts
Queries now return verified and recommended statuses from db
> Added checks for recommend and verified purchase for reviews

- src/components/cart/PreorderBody.tsx
- src/components/checkout/CartItemCard.tsx
- src/lib/utils/date.ts
- src/lib/utils/deliveryDateUtils.ts
Customers were concerned about the ship date so we're adding it into the checkout.
Calvin also requested to change EST ship date to 4 days instead of 5.
> Added Estimated Ship Date to Your Cart & EST Ship Date Changed From 5 to 4 days

- src/components/checkout/Payment.tsx
- src/components/ui/loading-button.tsx
When trying to checkout with an invalid card, order payment loads but nothing happens.
So I added the error message back in.
https://www.loom.com/share/f1abdf6688584827a283ee9fb0535efb?sid=b743d8a4-7350-4068-bec2-e3b31fac1830
> Invalid Card Error Message Before Order Review

- src/app/(main)/thank-you/components/KnoCommerceEmbed.tsx
- src/app/(main)/thank-you/page.tsx
- src/lib/utils/adminPanel.ts
Wanted to get some more customer input after they make a purchase
> Implementing KnoCommerce Survey

- src/app/(main)/[productType]/components/ProductContent.tsx
- src/app/(main)/seat-covers/components/SeatContent.tsx
Rivian reached out for IP enforcement
Suggested we say Car/Seat Cover for Rivian
> Updated to have rivian text say car/seat cover FOR rivian

- src/app/(main)/[productType]/components/CircleColorSelector.tsx
- src/lib/sendgrid/emails/questions.ts
> Color Text Added and Removed Vasiliy and William From Support Email 

- src/app/(main)/[productType]/[coverType]/[make]/[model]/[year]/page.tsx
- src/app/(main)/[productType]/[coverType]/[make]/[model]/page.tsx
- src/app/(main)/[productType]/[coverType]/[make]/page.tsx
- src/app/(main)/[productType]/[coverType]/page.tsx
- src/app/(main)/[productType]/page.tsx
- src/app/(main)/seat-covers/[coverType]/[make]/[model]/[year]/page.tsx
- src/app/(main)/seat-covers/[coverType]/[make]/[model]/page.tsx
- src/app/(main)/seat-covers/[coverType]/[make]/page.tsx
- src/app/(main)/seat-covers/[coverType]/page.tsx
Too many builds going on and making Vercel costs go up
Reducing the builds
> Updating revalidation from 5 minutes to 24 hours

- src/components/PDP/components/ReviewFilters.tsx
- src/components/PDP/components/ReviewSection.tsx
- src/components/PDP/components/ReviewSummaryHeader.tsx
- src/components/PDP/components/ReviewsLoadMoreButton.tsx
- src/contexts/ReviewContext.tsx
- src/hooks/review/useFilterHandler.tsx
- src/hooks/review/useSortHandler.tsx
- src/hooks/review/useViewMoreHandler.tsx
- Extract things into components to make it more readable 
- Extract state into a context to make it easier to manage
- Reduced amount of props / parameters needed and used context instead
> Review Code Refactor

- src/components/checkout/AddressForm.tsx
- src/components/checkout/BillingAddress.tsx
- src/components/checkout/CustomTextField.tsx
- src/lib/db/orders/updateOrders.ts
- src/lib/utils/stringHelpers.ts
When user goes through checkout, shipping and billing will be saved once shipping has been added.
Don't need them to finish checkout to get that information
> Partial Checkout Saving

- src/components/checkout/CheckoutAccordion.tsx
- src/components/checkout/PayPalButtonSection.tsx
- src/lib/sendgrid/emails/thank-you.ts
- src/lib/utils/deliveryDateUtils.ts
Customers were confused about pre-order.
Added some text if order is a preorder.
> Added preorder text for preorder emails

- src/components/checkout/CheckoutAccordion.tsx
- src/components/checkout/PayPalButtonSection.tsx
- src/lib/sendgrid/emails/thank-you.ts
- src/lib/utils/deliveryDateUtils.ts
Added preorder text for preorder emails #659
> Preview to Main: Preorder Text to Preorder Emails

- src/app/(main)/seat-covers/[coverType]/page.tsx
- src/app/(main)/seat-covers/page.tsx
- src/lib/db/constants/databaseTableNames.ts
- src/lib/db/seat-covers/index.ts
Seat Cover/Leather would load slow because has to load lot of data
Just made new RPC and had some default data for it
Top 10 of each color
https://supabase.com/dashboard/project/jxqclggjpttivrkogrce/sql/786d049f-9083-4767-a6fb-496cafbc2e00
> Added default seat color RPC

- src/app/api/meta/event/route.ts
Vasiliy asked for some logging cus things aren't matching up on Meta CAPI
> Added logging for meta CAPI

- src/app/api/meta/event/route.ts
Content wasn't showing cus it was nested object
> JSON stringfy the meta CAPI logging

- src/app/api/meta/event/route.ts
JSON stringfy the meta CAPI logging #671
> Preview to Main: 

- src/app/(main)/thank-you/page.tsx
- src/lib/db/admin-panel/orders.ts
Added getOrderById so Paypal can use order number to get information about customer and the order
> Implement KnoCommerce for Paypal

- src/app/(main)/seat-covers/components/SeatContent.tsx
- src/app/api/admin-panel/order-items/route.ts
- src/components/cart/AddToCart.tsx
Item name will include submodel if sku is missing from product
> Added submodel if sku is missing from product

- src/app/(main)/seat-covers/components/SeatContent.tsx
- src/app/api/admin-panel/order-items/route.ts
- src/components/cart/AddToCart.tsx
- src/lib/utils/stripe.ts
Added submodel if sku is missing from product #680
> Preview to Main: Include Submodel into Item Name if SKU is missing

- next.config.js
New images had new URL. Had to update next config to reflect this.
> Update next js config

- src/app/(main)/seat-covers/components/SeatCoverColorSelector.tsx
MSRP	Price
279.95	560
379.95	760
> Updating default seat cover price to 279.95 & 379.95

- src/app/(main)/seat-covers/components/SeatContent.tsx
- src/app/(main)/seat-covers/components/SeatCoverColorSelector.tsx
Updating default seat cover price to 279.95 & 379.95 #689
> Preview to Main: Update Default Seat Cover Price

- src/components/checkout/CheckoutAccordion.tsx
Not an issue but would cause errors. 
Confirmed sku lab still got the original orders
> Accidentally had two SKU Lab postings

- src/app/layout.tsx
Costing money so removing cus we're using Google Analytics
> Removed vercel analytics

- package-lock.json
- package.json
- src/app/layout.tsx
Curious on how this works so adding it
https://vercel.com/coverland-3615f02b/coverland-2-0/speed-insights
> Added Vercel Speed Insights

- src/app/layout.tsx
Merge this in when want to remove speed insights
> Remove speed insights

- src/app/layout.tsx
- src/components/checkout/CheckoutAccordion.tsx
- src/components/checkout/PayPalButtonSection.tsx
Updating discount for skulab to just be preorder discount #701
> Preview to Main: using Preorder Discount for SKU Labs

- src/components/checkout/CheckoutAccordion.tsx
- src/components/checkout/PayPalButtonSection.tsx
Made discount negative for sku lab discount #703
> Preview to Main: SKU Lab discount needs to be negative

- src/app/api/sku-labs/orders/route.ts
- src/components/checkout/CheckoutAccordion.tsx
- src/components/checkout/PayPalButtonSection.tsx
- src/lib/db/sku-labs/index.ts
Linking items wasn't working and causing it to crash
Had to add an await
> Forgot await for sku lab orders

- src/components/PDP/AskQuestionDesktop.tsx
- src/components/PDP/AskQuestionOpenTrigger.tsx
- src/components/ui/accordion.tsx
Had a button in a button and it was throwing some errors.
Also showPlus was not destructured properly so it was being sent into the DOM incorrectly
> Changed AskQuestionOpenTrigger from button to div

- src/components/cart/PreorderPreview.tsx
- src/components/hero/dropdown/SubmodelDropdown.tsx
Dropdown: Update parent generation when submodel1 is selected #719
> Preview to Main: Dropdown Parent Generation Updates on Submodel1 

- src/lib/db/sku-labs/index.ts
- src/lib/utils/skuLabs.ts
SKU Lab creation only detects items at the moment.
Added in a check for the display set and if it's Full Seat Set it will be a kit and look up that item
> Added kit detection to SKU Labs Order Creation

- src/lib/utils/skuLabs.ts
If order number includes 'PRE', add PRE-ORDER tag
> Added tag generation based on preorder

- src/app/(main)/seat-covers/components/SeatCoverColorSelector.tsx
Calvin wants us to remove Green and Navy. Not sure why, guessing it's low sell count.
> Removing green and navy from seat cover selector

- src/components/checkout/CheckoutAccordion.tsx
- src/pages/api/heartland/credit/charge.ts
Getting this message. Since it's a 04, payment doesn't go through.
```
[charge card response Transaction {
authorizedAmount: undefined,
avsAddressResponse: undefined,
balanceAmount: undefined,
pointsBalanceAmount: undefined,
cardBrandTransactionId: '464261593336690',
commercialIndicator: undefined,
responseCode: '04',
responseMessage: 'Success',
transactionDescriptor: undefined,
referenceNumber: '426169807892',
recurringDataCode: undefined,
cvnResponseMessage: 'Match.',
cvnResponseCode: 'M',
cavvResponseCode: undefined,
multiCapture: undefined,
multiCapturePaymentCount: undefined,
multiCaptureSequence: undefined,
cardLast4: undefined,
cardType: 'Visa',
avsResponseMessage: 'Neither address nor postal code match',
avsResponseCode: 'N',
availableBalance: undefined,
transactionReference: …
```
> Added error message for 04 Visa

- src/components/checkout/CheckoutAccordion.tsx
- src/lib/utils/adminPanel.ts
Just to see what some of the issues are, will have to iterate on this as more come in
> Save response code to notes if error

- src/components/checkout/CheckoutAccordion.tsx
- src/lib/utils/adminPanel.ts
- src/pages/api/heartland/credit/charge.ts
Save response code to notes if error #741
> Preview to Main: Saving Response Code To Notes On Error

- src/components/checkout/CheckoutAccordion.tsx
- src/lib/utils/heartland.ts
[https://cert.api2.heartlandportico.com/Gateway/PorticoDevGuide/build/PorticoDeveloperGuide/#Gateway Response Codes.html](https://cert.api2.heartlandportico.com/Gateway/PorticoDevGuide/build/PorticoDeveloperGuide/#Gateway%20Response%20Codes.html)
[https://cert.api2.heartlandportico.com/Gateway/PorticoDevGuide/build/PorticoDeveloperGuide/#Issuer Response Codes.html](https://cert.api2.heartlandportico.com/Gateway/PorticoDevGuide/build/PorticoDeveloperGuide/#Issuer%20Response%20Codes.html)
> Improved response code errors

- src/components/checkout/CheckoutAccordion.tsx
- src/lib/utils/heartland.ts
Missed 51, added message for it #749
> Preview to Main: Added 51 Response Code to Heartland

- src/components/checkout/CheckoutAccordion.tsx
> Updated sku lab order to come in as heartland

- src/components/checkout/CheckoutAccordion.tsx
- src/lib/utils/heartland.ts
Updated sku lab order to come in as heartland #751
> Preview to Main: Sku Lab Orders come in as Heartland now

- src/app/(main)/[productType]/components/VehicleCoverDetails.tsx
- src/app/(main)/seat-covers/components/SeatCoverDetails.tsx
Seat Cover Details would re-render whenever ExtraDetailsTab re-rendered and this would happen all the time.
Applied to Car Cover Details too
> Added react memo to seat cover details to reduce re-rendering

- src/app/(main)/seat-covers/components/SeatCoverColorSelector.tsx
/seat-covers/leather/toyota/corolla/2014-2019?submodel=sedan
Made it so the display color will stay the same even after changing display set.
> Selected Color Persists After Changing Display Set

- src/app/(main)/[productType]/components/FreeDetails.tsx
- src/app/(main)/thank-you/components/OrderConfirmationContent.tsx
- src/components/footer/Footer.tsx
- src/components/header/Header.tsx
- src/components/hero/dropdown/HeroDropdown.tsx
- src/components/policy/ContactPage.tsx
- src/components/policy/PrivacyPolicyContent.tsx
- src/components/policy/ReturnPolicyContent.tsx
- src/components/ui/annoucement-dialog.tsx
- src/components/ui/banner.tsx
- src/lib/sendgrid/emails/contact.ts
- src/lib/sendgrid/emails/questions.ts
Issue where support email got banned
Created a banner and pop up announcement
The Z level is fucked because someone else decided to put random z-levels somewhere else and I dont' have the time to fix the z-level so now /I'M/ doing something weird with the z-level and dialog overlay.
Changing support@coverland.com -> cs@coverland.com
> Customer Service Announcement

- src/app/(main)/[productType]/components/FreeDetails.tsx
- src/app/(main)/thank-you/components/OrderConfirmationContent.tsx
- src/components/footer/Footer.tsx
- src/components/header/Header.tsx
- src/components/policy/ContactPage.tsx
- src/components/policy/PrivacyPolicyContent.tsx
- src/components/policy/ReturnPolicyContent.tsx
- src/components/ui/annoucement-dialog.tsx
- src/lib/sendgrid/emails/contact.ts
- src/lib/sendgrid/emails/questions.ts
Reverted cs@coverland.com to support@coverland.com #772
> Preview to Main: Revert cs@coverland.com to support@coverland.com

- src/app/(main)/floor-mats/[coverType]/[make]/[model]/[year]/page.tsx
- src/app/(main)/floor-mats/[coverType]/[make]/[model]/page.tsx
- src/app/(main)/floor-mats/[coverType]/[make]/page.tsx
- src/app/(main)/floor-mats/[coverType]/page.tsx
Floor Mats ᐉ Coverland ⭐ Free, Same-Day Shipping ✔️ Free Returns & Purchase Protection ✔️ Custom-fit, all-weather car mats 🌦️ with a 10-year warranty 🛡️ and odor-free materials.
Anti-slip, flexible 🤸, and designed for full edge protection.
Easy to clean 🧼 and built to withstand any climate.
Enjoy 4.7-star quality, free returns, and direct pricing savings 💰!
> Updated floor mat metadata

- src/components/PDP/ProductDetailsDescription/FloorMat/AllSeasonIcons.tsx
- src/components/PDP/ProductDetailsPanel/ProductDetailsPanel.tsx
- src/components/PDP/ProductDetailsPanel/ProductInfo.tsx
- src/components/PDP/ProductDetailsPanel/ProductPricing.tsx
- src/components/PDP/components/ExtraDetailsTabs.tsx
- src/hooks/review/useFilterHandler.tsx
- src/hooks/review/useSortHandler.tsx
- src/lib/constants.tsx
- src/lib/db/constants/databaseTableNames.ts
- src/lib/db/review/index.ts
Reviews for Floor Mats.
Currently missing some information 
- author
- rating 
- helpful
- recommended
- verified
I filled in rating to 5, helpful to 0, recommend and verified to yes.
> Floor Mat Review Implemented
